server:
  port: 5000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka

spring:
  application:
    name: bestdeals-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
      - id: request-processor
        uri: lb://BESTDEALS-REQUEST-PROCESSOR
        predicates:
        - Path=/request-api/**